"""Validate worker results and record/check terminal worker dispositions."""

import argparse
from dataclasses import dataclass
import json
import os
from pathlib import Path
import sys

from . import records
from . import review_dispositions


MAX_REVISION = 2**63 - 1
RESULT_REQUIRED_FIELDS = (
    "task_id",
    "assignment_revision",
    "outcome",
    "summary",
    "artifacts",
    "checks",
    "unresolved",
    "next_action",
)
RESULT_OPTIONAL_FIELDS = ("candidate",)
CANDIDATE_FIELDS = ("repo", "branch", "base", "head")
ARTIFACT_FIELDS = ("path", "kind")
CHECK_FIELDS = ("name", "status", "evidence")
DISPOSITION_FIELDS = {
    "task_id",
    "assignment_revision",
    "disposition",
    "summary",
    "evidence",
}
TERMINAL_DISPOSITIONS = {"completed", "blocked", "failed", "cancelled"}
RESULT_OUTCOMES = {"ready", "blocked", "failed"}
CHECK_STATUSES = {"passed", "failed", "not_run"}
OUTCOME_NORMALIZATIONS = {"complete": "ready", "completed": "ready"}
WORKER_MARKERS = {"brief.md", "result.json", "disposition.json"}
OVERWRITE_MESSAGE = "disposition already exists: {path}; pass --replace to update it"


@dataclass(frozen=True)
class WorkerIdentity:
    task_id: str
    assignment_revision: int


@dataclass(frozen=True)
class WorkerEntry:
    identity: WorkerIdentity
    directory: Path


@dataclass(frozen=True)
class DispositionInput:
    identity: WorkerIdentity
    disposition: str
    summary: str
    evidence: str


def _read_json(path, label):
    try:
        return records.load_json(path)
    except FileNotFoundError as error:
        records.invalid(f"missing {label} at {path}")
    except records.JobError as error:
        records.invalid(f"{label} at {path}: {error}")
    except OSError as error:
        records.invalid(f"cannot read {label} at {path}: {error.strerror or error}")


def _choice(value, choices, label):
    value = records.text(value, label)
    if value not in choices:
        records.invalid(f"{label} must be one of: {', '.join(sorted(choices))}")
    return value


def _check_identity(record, expected, label):
    if record["task_id"] != expected.task_id:
        records.invalid(
            f"{label} task_id mismatch: expected {expected.task_id!r}, got {record['task_id']!r}"
        )
    if record["assignment_revision"] != expected.assignment_revision:
        records.invalid(
            f"{label} assignment_revision mismatch: expected {expected.assignment_revision}, "
            f"got {record['assignment_revision']!r}"
        )


def _validate_candidate(candidate):
    candidate = records.fields(candidate, CANDIDATE_FIELDS, label="candidate")
    for key in CANDIDATE_FIELDS:
        records.text(candidate[key], f"candidate.{key}")


def result_schema_markdown():
    """Render the worker result contract from the validator's field and enum definitions."""
    example_values = {
        "task_id": "task-id",
        "assignment_revision": 1,
        "outcome": "ready",
        "summary": "What was produced and what it establishes.",
        "artifacts": [{"path": "artifact-path", "kind": "report"}],
        "checks": [{"name": "check", "status": "passed", "evidence": "evidence-path"}],
        "unresolved": [],
        "next_action": "Present the artifact to the user.",
    }
    example = {field: example_values[field] for field in RESULT_REQUIRED_FIELDS}
    candidate = {key: f"{key}-value" for key in CANDIDATE_FIELDS}
    required = ", ".join(f"`{field}`" for field in RESULT_REQUIRED_FIELDS)
    optional = ", ".join(f"`{field}`" for field in RESULT_OPTIONAL_FIELDS)
    outcomes = ", ".join(f"`{value}`" for value in sorted(RESULT_OUTCOMES))
    statuses = ", ".join(f"`{value}`" for value in sorted(CHECK_STATUSES))
    artifact_fields = ", ".join(f"`{field}`" for field in ARTIFACT_FIELDS)
    check_fields = ", ".join(f"`{field}`" for field in CHECK_FIELDS)
    candidate_fields = ", ".join(f"`{field}`" for field in CANDIDATE_FIELDS)
    return "\n".join((
        "## Worker result record (generated by `worker-records.py schema --format md`)",
        "",
        "Copy this whole section verbatim into each worker brief or per-run CONTRACT. "
        "Do not rewrite the example or allowed values.",
        "",
        "```json",
        json.dumps(example, indent=2, ensure_ascii=False),
        "```",
        "",
        f"Required top-level fields: {required}.",
        f"Optional top-level fields: {optional}; omit `candidate` for non-repository tasks.",
        f"`outcome` must be one of {outcomes}; `assignment_revision` must be an "
        f"integer from 1 to {MAX_REVISION}.",
        "`task_id` and `assignment_revision` must match the identity supplied to `validate-result`.",
        "Text values must be non-empty strings with no NUL and at most 100,000 characters.",
        f"`artifacts` is an array of objects with exactly {artifact_fields}; it may be "
        "empty only when the outcome is not `ready`.",
        f"`checks` is an array of objects with exactly {check_fields}; `status` must "
        f"be one of {statuses}.",
        "`unresolved` is an array of non-empty strings; `blocked` and `failed` "
        "require at least one explanatory item.",
        "For repository changes, validate with `--repository-changes` and include "
        f"`candidate` with exactly {candidate_fields}.",
        "When present, `candidate` must be an object with non-empty string values.",
        "Unknown fields and duplicate JSON keys are invalid.",
        "",
        "Repository-change candidate shape:",
        "",
        "```json",
        json.dumps({"candidate": candidate}, indent=2, ensure_ascii=False),
        "```",
    )) + "\n"


def validate_result(path, identity, repository_changes=False):
    _validate_result_record(_read_json(path, "result.json"), identity, repository_changes)


def _validate_result_record(record, identity, repository_changes=False):
    record = records.fields(
        record,
        RESULT_REQUIRED_FIELDS,
        RESULT_OPTIONAL_FIELDS,
        "result.json",
    )
    records.text(record["task_id"], "task_id")
    records.integer(record["assignment_revision"], "assignment_revision", 1, MAX_REVISION)
    _check_identity(record, identity, "result.json")
    _choice(record["outcome"], RESULT_OUTCOMES, "outcome")
    records.text(record["summary"], "summary")
    records.text(record["next_action"], "next_action")

    artifacts = record["artifacts"]
    if not isinstance(artifacts, list):
        records.invalid("artifacts must be an array")
    for index, item in enumerate(artifacts):
        item = records.fields(item, ARTIFACT_FIELDS, label=f"artifacts[{index}]")
        records.text(item["path"], f"artifacts[{index}].path")
        records.text(item["kind"], f"artifacts[{index}].kind")
    if record["outcome"] == "ready" and not artifacts:
        records.invalid("ready result requires at least one artifact")

    checks = record["checks"]
    if not isinstance(checks, list):
        records.invalid("checks must be an array")
    for index, item in enumerate(checks):
        item = records.fields(
            item,
            CHECK_FIELDS,
            label=f"checks[{index}]",
        )
        records.text(item["name"], f"checks[{index}].name")
        _choice(item["status"], CHECK_STATUSES, f"checks[{index}].status")
        records.text(item["evidence"], f"checks[{index}].evidence")

    unresolved = record["unresolved"]
    if not isinstance(unresolved, list):
        records.invalid("unresolved must be an array")
    for index, item in enumerate(unresolved):
        records.text(item, f"unresolved[{index}]")
    if record["outcome"] in {"blocked", "failed"} and not unresolved:
        records.invalid("blocked and failed results require an explanatory unresolved item")

    if "candidate" in record:
        _validate_candidate(record["candidate"])
    if repository_changes and "candidate" not in record:
        records.invalid("candidate record is required for repository changes")


def normalize_result(source, output, identity, repository_changes=False):
    source = Path(source)
    output = Path(output)
    try:
        same_file = source.resolve() == output.resolve()
    except (OSError, RuntimeError):
        records.invalid("result input and output paths cannot be resolved safely")
    if same_file:
        records.invalid("normalized result output must differ from the input path")

    record = _read_json(source, "result.json")
    changes = []
    if isinstance(record, dict):
        if not repository_changes and record.get("candidate", object()) is None:
            del record["candidate"]
            changes.append({"path": "candidate", "action": "removed null optional candidate"})

        outcome = record.get("outcome")
        if isinstance(outcome, str) and outcome in OUTCOME_NORMALIZATIONS:
            record["outcome"] = OUTCOME_NORMALIZATIONS[outcome]
            changes.append({
                "path": "outcome",
                "action": "mapped complete/completed to ready",
            })

        artifacts = record.get("artifacts")
        if isinstance(artifacts, list):
            for index, item in enumerate(artifacts):
                if isinstance(item, dict) and set(item) == {"path"}:
                    item["kind"] = "artifact"
                    changes.append({
                        "path": f"artifacts[{index}].kind",
                        "action": "filled missing kind as artifact",
                    })

        checks = record.get("checks")
        if isinstance(checks, list):
            for index, item in enumerate(checks):
                if isinstance(item, str):
                    checks[index] = {
                        "name": item,
                        "status": "not_run",
                        "evidence": "Bare-string check supplied no status or evidence.",
                    }
                    changes.append({
                        "path": f"checks[{index}]",
                        "action": "wrapped bare-string check as not_run",
                    })

    _validate_result_record(record, identity, repository_changes)
    try:
        records.atomic_bytes(output, records.encoded(record) + b"\n")
    except OSError as error:
        records.invalid(f"cannot write normalized result at {output}: {error.strerror or error}")
    return {"source": str(source), "output": str(output), "changes": changes}


def _validate_disposition(record, worker):
    record = records.fields(record, DISPOSITION_FIELDS, label="disposition.json")
    records.text(record["task_id"], "disposition.task_id")
    records.integer(
        record["assignment_revision"],
        "disposition.assignment_revision",
        1,
        MAX_REVISION,
    )
    _check_identity(record, worker.identity, "disposition.json")
    _choice(record["disposition"], TERMINAL_DISPOSITIONS, "disposition")
    records.text(record["summary"], "disposition.summary")
    records.text(record["evidence"], "disposition.evidence")


def _relative_directory(value, label):
    value = records.text(value, label)
    parts = value.split("/")
    if value.startswith("/") or "\\" in value or any(part in {"", ".", ".."} for part in parts):
        records.invalid(f"{label} must stay inside the run directory")
    return Path(*parts)


def _parse_roster(run_dir):
    roster_path = run_dir / "workers.json"
    if roster_path.is_symlink():
        records.invalid("workers.json must not be a symlink")
    if not roster_path.exists():
        return []
    roster = records.fields(_read_json(roster_path, "workers.json"), {"workers"}, label="workers.json")
    if not isinstance(roster["workers"], list):
        records.invalid("workers.json.workers must be an array")

    entries = []
    seen_task_ids = set()
    seen_directories = set()
    for index, item in enumerate(roster["workers"]):
        label = f"workers.json.workers[{index}]"
        item = records.fields(
            item,
            {"task_id", "assignment_revision", "directory"},
            label=label,
        )
        task_id = records.text(item["task_id"], f"{label}.task_id")
        revision = records.integer(
            item["assignment_revision"],
            f"{label}.assignment_revision",
            1,
            MAX_REVISION,
        )
        directory = _relative_directory(item["directory"], f"{label}.directory")
        if task_id in seen_task_ids:
            records.invalid(f"workers.json has duplicate task_id {task_id!r}")
        if directory in seen_directories:
            records.invalid(f"workers.json has duplicate directory {directory.as_posix()!r}")
        seen_task_ids.add(task_id)
        seen_directories.add(directory)
        entries.append(WorkerEntry(WorkerIdentity(task_id, revision), directory))
    return entries


def _discover_worker_directories(run_root):
    discovered = set()
    symlink_directories = []

    def fail_walk(error):
        raise error

    try:
        for current, directory_names, filenames in os.walk(
            run_root,
            topdown=True,
            followlinks=False,
            onerror=fail_walk,
        ):
            current_path = Path(current)
            traversable = []
            for name in directory_names:
                directory = current_path / name
                if directory.is_symlink():
                    symlink_directories.append(directory.relative_to(run_root))
                else:
                    traversable.append(name)
            directory_names[:] = traversable

            if current_path != run_root and WORKER_MARKERS.intersection(filenames):
                discovered.add(current_path.relative_to(run_root))
    except OSError as error:
        records.invalid(f"cannot inspect run directory {run_root}: {error.strerror or error}")
    return discovered, symlink_directories


def _validate_roster_directories(run_root, workers):
    issues = []
    safe_directories = set()
    for worker in workers:
        worker_dir = run_root / worker.directory
        try:
            resolved = worker_dir.resolve()
        except (OSError, RuntimeError):
            issues.append(
                f"worker {worker.identity.task_id!r}: directory cannot be resolved safely"
            )
            continue
        if not resolved.is_relative_to(run_root):
            issues.append(
                f"worker {worker.identity.task_id!r}: directory resolves outside the run directory"
            )
        else:
            safe_directories.add(worker.directory)
    return safe_directories, issues


def record_disposition(worker_dir, disposition, replace=False):
    if worker_dir.is_symlink() or not worker_dir.is_dir():
        records.invalid(f"worker directory does not exist or is a symlink: {worker_dir}")
    records.text(disposition.identity.task_id, "task_id")
    records.integer(
        disposition.identity.assignment_revision,
        "assignment_revision",
        1,
        MAX_REVISION,
    )
    _choice(disposition.disposition, TERMINAL_DISPOSITIONS, "disposition")
    records.text(disposition.summary, "summary")
    records.text(disposition.evidence, "evidence")

    record = {
        "task_id": disposition.identity.task_id,
        "assignment_revision": disposition.identity.assignment_revision,
        "disposition": disposition.disposition,
        "summary": disposition.summary,
        "evidence": disposition.evidence,
    }
    target = worker_dir / "disposition.json"
    if (target.exists() or target.is_symlink()) and not replace:
        records.invalid(OVERWRITE_MESSAGE.format(path=target))
    try:
        records.atomic_bytes(target, records.encoded(record) + b"\n")
    except OSError as error:
        records.invalid(f"cannot write disposition.json at {target}: {error.strerror or error}")


def check_closeout(run_dir):
    if run_dir.is_symlink() or not run_dir.is_dir():
        records.invalid(f"run directory does not exist or is a symlink: {run_dir}")
    run_root = run_dir.resolve()
    workers = _parse_roster(run_dir)
    discovered, symlink_directories = _discover_worker_directories(run_root)
    roster_directories = {worker.directory for worker in workers}
    safe_directories, issues = _validate_roster_directories(run_root, workers)

    for directory in sorted(discovered - roster_directories, key=Path.as_posix):
        issues.append(
            f"unrostered worker-shaped directory: {directory.as_posix()}"
        )
    for directory in sorted(symlink_directories, key=Path.as_posix):
        issues.append(f"cannot inspect symlinked directory: {directory.as_posix()}")

    for worker in workers:
        if worker.directory not in safe_directories:
            continue
        worker_dir = run_root / worker.directory
        if not worker_dir.is_dir():
            issues.append(
                f"worker {worker.identity.task_id!r}: worker directory is missing: "
                f"{worker.directory.as_posix()}"
            )
            continue
        disposition_path = worker_dir / "disposition.json"
        try:
            record = _read_json(disposition_path, "disposition.json")
            _validate_disposition(record, worker)
        except records.JobError as error:
            issues.append(
                f"worker {worker.identity.task_id!r} revision "
                f"{worker.identity.assignment_revision}: {error}"
            )

    if issues:
        details = "\n".join(f"- {issue}" for issue in issues)
        records.invalid(f"CLOSEOUT INCOMPLETE:\n{details}")
    return len(workers)


def positive_integer(value):
    if not value.isascii() or not value.isdigit():
        raise argparse.ArgumentTypeError("must be a positive integer")
    parsed = int(value)
    if parsed < 1 or parsed > MAX_REVISION:
        raise argparse.ArgumentTypeError("must be a positive integer")
    return parsed


def build_parser():
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)

    schema_parser = commands.add_parser(
        "schema", help="print the current worker result contract"
    )
    schema_parser.add_argument("--format", choices=("md",), default="md")

    normalize_parser = commands.add_parser(
        "normalize-result", help="repair known benign result shapes and validate the copy"
    )
    normalize_parser.add_argument("result_json", type=Path)
    normalize_parser.add_argument("--output", type=Path, required=True)
    normalize_parser.add_argument("--task-id", required=True)
    normalize_parser.add_argument("--revision", type=positive_integer, required=True)
    normalize_parser.add_argument("--repository-changes", action="store_true")

    result_parser = commands.add_parser("validate-result", help="validate one worker result.json")
    result_parser.add_argument("result_json", type=Path)
    result_parser.add_argument("--task-id", required=True)
    result_parser.add_argument("--revision", type=positive_integer, required=True)
    result_parser.add_argument("--repository-changes", action="store_true")

    disposition_parser = commands.add_parser("record-disposition", help="write a terminal coordinator disposition")
    disposition_parser.add_argument("worker_dir", type=Path)
    disposition_parser.add_argument("--task-id", required=True)
    disposition_parser.add_argument("--revision", type=positive_integer, required=True)
    disposition_parser.add_argument("--status", choices=sorted(TERMINAL_DISPOSITIONS), required=True)
    disposition_parser.add_argument("--summary", required=True)
    disposition_parser.add_argument("--evidence", required=True)
    disposition_parser.add_argument("--replace", action="store_true")

    closeout_parser = commands.add_parser("check-closeout", help="require a terminal disposition for every worker")
    closeout_parser.add_argument("run_dir", type=Path)

    sync_parser = commands.add_parser(
        "sync-dispositions",
        help="copy coordinator dispositions from review-response.md into review evidence",
    )
    sync_parser.add_argument("task_dir", type=Path)
    return parser


def main(argv=None):
    parser = build_parser()
    args = parser.parse_args(argv)
    try:
        if args.command == "schema":
            print(result_schema_markdown(), end="")
            return 0
        if args.command == "normalize-result":
            identity = WorkerIdentity(args.task_id, args.revision)
            audit = normalize_result(
                args.result_json,
                args.output,
                identity,
                repository_changes=args.repository_changes,
            )
            print(json.dumps(audit, ensure_ascii=False, sort_keys=True))
            return 0
        if args.command == "validate-result":
            identity = WorkerIdentity(args.task_id, args.revision)
            validate_result(
                args.result_json,
                identity,
                repository_changes=args.repository_changes,
            )
            print(f"VALID: {args.result_json}")
            return 0
        if args.command == "record-disposition":
            disposition = DispositionInput(
                WorkerIdentity(args.task_id, args.revision),
                args.status,
                args.summary,
                args.evidence,
            )
            record_disposition(args.worker_dir, disposition, replace=args.replace)
            print(f"RECORDED: {args.worker_dir / 'disposition.json'}")
            return 0
        if args.command == "sync-dispositions":
            count = review_dispositions.sync_dispositions(args.task_dir)
            if count:
                print(f"SYNCED: {count} review evidence file(s)")
            else:
                print("SYNCED: dispositions already match review evidence")
            return 0
        count = check_closeout(args.run_dir)
        print(f"CLOSEOUT READY: {count} worker(s) have terminal dispositions.")
        return 0
    except records.JobError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    raise SystemExit(main())
